name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        id: install-package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[dev]'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
